In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_excel("dataset.xlsx")

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6167 entries, 0 to 6166
Columns: 136 entries, ind_5 to 90_target
dtypes: float64(88), int64(45), object(3)
memory usage: 6.3+ MB

In [4]:
copydata=data.copy()

In [5]:
copydata=copydata.replace('?',np.nan)
copydata=copydata.dropna(axis=0,how="any")

In [6]:
target1=copydata["20_target"]
target2=copydata["50_target"]
target3=copydata["90_target"]

In [7]:
untargetdata=copydata.drop(["20_target","50_target","90_target"],axis=1)

In [8]:
untargetdata.columns[:75] #ind_109 objects değişken

Index(['ind_5', 'ind_6', 'ind_8', 'ind_9', 'ind_10', 'ind_12', 'ind_13',
       'ind_14', 'ind_15', 'ind_16', 'ind_17', 'ind_18', 'ind_19', 'ind_20',
       'ind_21', 'ind_22', 'ind_23', 'ind_25', 'ind_26', 'ind_27', 'ind_28',
       'ind_29', 'ind_30', 'ind_31', 'ind_32', 'ind_33', 'ind_34', 'ind_35',
       'ind_36', 'ind_37', 'ind_39', 'ind_40', 'ind_41', 'ind_42', 'ind_43',
       'ind_44', 'ind_45', 'ind_46', 'ind_47', 'ind_48', 'ind_49', 'ind_50',
       'ind_51', 'ind_52', 'ind_53', 'ind_56', 'ind_58', 'ind_61', 'ind_62',
       'ind_65', 'ind_67', 'ind_70', 'ind_71', 'ind_74', 'ind_77', 'ind_82',
       'ind_83', 'ind_88', 'ind_92', 'ind_102', 'ind_109', 'ind_116',
       'ind_118', 'ind_122', 'ind_124', 'ind_128', 'ind_130', 'ind_132',
       'ind_134', 'ind_136', 'ind_139', 'ind_142', 'ind_145', 'ind_147',
       'ind_150'],
      dtype='object')

In [9]:
x_dummy=pd.get_dummies(untargetdata[["ind_109"]])

In [10]:
x_dummy

      ind_109_GREEN  ind_109_RED
0                 1            0
1                 1            0
2                 1            0
3                 1            0
4                 1            0
...             ...          ...
6162              0            1
6163              0            1
6164              1            0
6165              1            0
6166              1            0

[5126 rows x 2 columns]

In [11]:
untargetdata=untargetdata.drop(["ind_109"],axis=1)

In [12]:
untargetdata

,ind_5,ind_6,ind_8,ind_9,ind_10,ind_12,ind_13,ind_14,ind_15,ind_16,...,ind_410,ind_412,ind_414,ind_416,ind_418,ind_420,ind_422,ind_424,ind_426,ind_428
0,19,17,100.000000,85.714286,14.285714,72.363515,60.808814,23.80,17.62,11.73,...,-27,0.002371,2.0,-49.6,-54,-152.0,-353.0,1.000000,0.498547,0.701906
1,24,19,100.000000,78.571429,21.428571,74.275883,64.366798,11.45,18.16,12.22,...,-31,0.003074,0.8,-55.6,-60,-158.0,-359.0,1.000000,0.537088,0.690833
2,30,24,100.000000,71.428571,28.571429,75.140402,65.915803,8.75,17.86,12.28,...,-30,0.003561,2.7,-58.4,-60,-160.0,-362.0,1.000000,0.615169,0.693040
3,37,30,100.000000,64.285714,35.714286,76.677846,68.584234,7.80,14.76,12.61,...,-30,0.004366,0.9,-61.8,-65,-166.0,-367.0,1.000000,0.661517,0.673418
4,41,37,100.000000,57.142857,42.857143,81.603007,76.455495,14.90,11.92,14.25,...,-45,0.004198,0.1,-79.8,-86,-186.0,-388.0,1.000000,0.747204,0.700522
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6162,27,31,57.142857,28.571429,28.571429,60.010531,32.362582,9.70,9.38,13.66,...,4,0.004633,14.7,-28.2,-40,-11.0,-270.0,0.270270,0.840000,0.600846
6163,22,27,50.000000,21.428571,28.571429,60.209998,32.914628,7.65,8.84,11.79,...,5,0.008511,14.3,-28.6,-41,-12.0,-271.0,0.000000,0.737470,0.527673
6164,19,22,42.857143,14.285714,28.571429,64.329611,43.550592,8.95,9.06,10.30,...,-3,0.008848,5.7,-37.2,-49,-21.0,-280.0,0.769231,0.632107,0.551759
6165,19,19,100.000000,7.142857,92.857143,69.027764,54.130755,13.55,10.36,10.55,...,-14,0.008940,1.4,-48.9,-61,-33.0,-292.0,1.000000,0.733010,0.591584
6166,19,19,92.857143,0.000000,92.857143,65.157180,45.524973,11.45,10.16,9.68,...,-8,0.008685,6.3,-44.0,-56,-28.0,-288.0,1.000000,0.687500,0.593936

In [13]:
pcaData=pd.concat([untargetdata,x_dummy],axis=1)

In [14]:
pcaData

,ind_5,ind_6,ind_8,ind_9,ind_10,ind_12,ind_13,ind_14,ind_15,ind_16,...,ind_414,ind_416,ind_418,ind_420,ind_422,ind_424,ind_426,ind_428,ind_109_GREEN,ind_109_RED
0,19,17,100.000000,85.714286,14.285714,72.363515,60.808814,23.80,17.62,11.73,...,2.0,-49.6,-54,-152.0,-353.0,1.000000,0.498547,0.701906,1,0
1,24,19,100.000000,78.571429,21.428571,74.275883,64.366798,11.45,18.16,12.22,...,0.8,-55.6,-60,-158.0,-359.0,1.000000,0.537088,0.690833,1,0
2,30,24,100.000000,71.428571,28.571429,75.140402,65.915803,8.75,17.86,12.28,...,2.7,-58.4,-60,-160.0,-362.0,1.000000,0.615169,0.693040,1,0
3,37,30,100.000000,64.285714,35.714286,76.677846,68.584234,7.80,14.76,12.61,...,0.9,-61.8,-65,-166.0,-367.0,1.000000,0.661517,0.673418,1,0
4,41,37,100.000000,57.142857,42.857143,81.603007,76.455495,14.90,11.92,14.25,...,0.1,-79.8,-86,-186.0,-388.0,1.000000,0.747204,0.700522,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6162,27,31,57.142857,28.571429,28.571429,60.010531,32.362582,9.70,9.38,13.66,...,14.7,-28.2,-40,-11.0,-270.0,0.270270,0.840000,0.600846,0,1
6163,22,27,50.000000,21.428571,28.571429,60.209998,32.914628,7.65,8.84,11.79,...,14.3,-28.6,-41,-12.0,-271.0,0.000000,0.737470,0.527673,0,1
6164,19,22,42.857143,14.285714,28.571429,64.329611,43.550592,8.95,9.06,10.30,...,5.7,-37.2,-49,-21.0,-280.0,0.769231,0.632107,0.551759,1,0
6165,19,19,100.000000,7.142857,92.857143,69.027764,54.130755,13.55,10.36,10.55,...,1.4,-48.9,-61,-33.0,-292.0,1.000000,0.733010,0.591584,1,0
6166,19,19,92.857143,0.000000,92.857143,65.157180,45.524973,11.45,10.16,9.68,...,6.3,-44.0,-56,-28.0,-288.0,1.000000,0.687500,0.593936,1,0

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test=train_test_split(pcaData,target3,test_size = 0.20 , random_state = 42)

In [17]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale

In [18]:
pca=PCA()

In [19]:
bilesenler=pca.fit_transform(scale(x_train))

In [20]:
np.cumsum(np.round(pca.explained_variance_ratio_, decimals= 4))*100

array([36.88, 49.26, 55.09, 59.51, 62.85, 65.74, 68.28, 70.28, 72.14,
       73.85, 75.42, 76.88, 78.25, 79.52, 80.74, 81.91, 83.02, 83.95,
       84.8 , 85.63, 86.44, 87.19, 87.87, 88.51, 89.12, 89.71, 90.25,
       90.75, 91.22, 91.67, 92.08, 92.49, 92.89, 93.26, 93.61, 93.95,
       94.27, 94.57, 94.86, 95.15, 95.42, 95.66, 95.89, 96.12, 96.33,
       96.53, 96.72, 96.89, 97.06, 97.22, 97.37, 97.51, 97.65, 97.78,
       97.91, 98.03, 98.14, 98.24, 98.33, 98.42, 98.5 , 98.58, 98.66,
       98.74, 98.81, 98.88, 98.95, 99.01, 99.07, 99.13, 99.18, 99.23,
       99.28, 99.32, 99.36, 99.4 , 99.44, 99.47, 99.5 , 99.53, 99.56,
       99.59, 99.62, 99.65, 99.68, 99.7 , 99.72, 99.74, 99.76, 99.78,
       99.8 , 99.82, 99.83, 99.84, 99.85, 99.86, 99.87, 99.88, 99.89,
       99.9 , 99.91, 99.92, 99.93, 99.94, 99.95, 99.95, 99.95, 99.95,
       99.95, 99.95, 99.95, 99.95, 99.95, 99.95, 99.95, 99.95, 99.95,
       99.95, 99.95, 99.95, 99.95, 99.95, 99.95, 99.95, 99.95, 99.95,
       99.95, 99.95, 99.95, 99.95, 99.95, 99.95, 99.95, 99.95])

In [21]:
pca=PCA(n_components=10)

In [22]:
bilesenler2=pca.fit_transform(scale(x_train))

In [23]:
from sklearn.linear_model import LinearRegression

In [27]:
lm1=LinearRegression()
pcr_model1=lm1.fit(bilesenler2,y_train)

In [28]:
predict_result=pcr_model1.predict(bilesenler2)

In [29]:
predict_result[:10]

array([ -9.19752056,  -3.19988783,  -1.21671304,   4.48408005,
       -13.98529889,  -8.92061076,  -3.15023088,   7.06724346,
        -5.66583193,  -4.76146007])

In [30]:
from sklearn.metrics import mean_squared_error,r2_score

In [31]:
r2_score(y_train,predict_result)

0.04187542963134716

In [33]:
pcr_model1=lm1.fit(bilesenler,y_train) 
predict_result2=pcr_model1.predict(bilesenler)

In [34]:
r2_score(y_train,predict_result2)

0.2136616658639232